1146 - Show completion screen only when all question are done
tapestry-tool/tapestry-wp pull request #1147
Opened 2021-10-27 02:43 UTC by EldadZZipori

## Changes
* Checking whether the question is last before showing completion screen
* Scrolling the user back to the top of the section in MultiContent view whenever necessary
* (In MultiContent view) Going back to the answer of the first question when the "Done"/"Continue" completion button is clicked, and there are no more unanswered questions after the current one.
* Adding a toggle for "customized/not customized" to the Confirmation customization section of the ActivityForm. If this toggle is on, display the form to customize the title and message, and count the confirmation screen as customized.

## Change Details
For backwards compatibility, customization is now considered "on" (and the toggle will be toggled on) if title or message strings are not empty.

## Screenshots
Custom confirmation toggle:

https://user-images.githubusercontent.com/44929104/170799443-f32dbdc7-730a-4d5f-932c-c1330d0a6fc0.mov

## Issue Linkage
Closes #1146 
## PR Dependency
Depends on: N/A

2022-05-26 00:13 UTC, legendword commented
@zifgu Try and see if you can replicate https://github.com/tapestry-tool/tapestry-wp/issues/1146#issuecomment-1133393108, if not we don't have to worry about it for now. Just test against the descriptions here: https://github.com/tapestry-tool/tapestry-wp/issues/1146#issue-1035491940

2022-05-26 21:39 UTC, zifgu commented
Confirming that only custom confirmation screens and the confirmation screen on the last question are shown.

The completion button sometimes goes back to the answer of the first question even when some questions are not completed – e.g. if the first question is not completed. I think this is because it only looks for unanswered questions after the active question. I might suggest either editing the description or the logic to match.

https://user-images.githubusercontent.com/44929104/170583893-bec24b9c-7849-4a03-9a05-cff0a235ada2.mov

Also, if you first set a custom confirmation title/message, then delete it, a confirmation screen still shows up even though the text is no longer customized.

https://user-images.githubusercontent.com/44929104/170584379-c9ce1428-a93a-49bc-a1b5-95703c355d56.mov

> @zifgu Try and see if you can replicate [#1146 (comment)](https://github.com/tapestry-tool/tapestry-wp/issues/1146#issuecomment-1133393108), if not we don't have to worry about it for now.

I was not able to replicate this issue when submitting the second-last question, or when editing the answer of the second-last question. Do you have any more information about the conditions where this issue occurs?

2022-05-26 22:23 UTC, legendword commented
Regarding your comment on deleted confirmation message:

I tested it on my end and deleting the confirmation title works, but deleting the message does not. I took a look into the actual stored content of that and it appears that the rich text editor retains an empty paragraph tag when you delete a line. This causes the code to detect that there actually is custom message. I've known this issue in almost every rich text editor... I guess this is why the code authors working on this PR before didn't include the check for non-empty confirmation messages. So the best solution I could come up with is simply not check for non-empty confirmation message, meaning we ASSUME that a custom confirmation message must always be accompanied by a custom confirmation title.

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/12668055/170589188-82e803a8-51aa-4092-a506-146610ac30e2.png">

2022-05-26 22:27 UTC, legendword commented
> I was not able to replicate this issue when submitting the second-last question, or when editing the answer of the second-last question. Do you have any more information about the conditions where this issue occurs?

It was a very random thing that happened, I myself could not even replicate that issue, so I'd suggest not worrying about it too much until we see it consistently.

Lastly, returning to the answer of the first question is intended behavior according to Aidin, but obviously if you leave the first question unanswered it would be kind of weird. I am not sure what to do about this; personally I would say this situation is very rare, but I will let Aidin decide on this one.

2022-05-26 23:25 UTC, zifgu commented
> I'd suggest not worrying about it too much until we see it consistently.
> 
> Lastly, returning to the answer of the first question is intended behavior according to Aidin, but obviously if you leave the first question unanswered it would be kind of weird. I am not sure what to do about this; personally I would say this situation is very rare, but I will let Aidin decide on this one.

Sounds good. I also think the current behaviour isn't confusing, especially since the answer screen shows an informative message when the question is unanswered. In that case, I can update the PR description to match the behaviour of the completion button.

2022-05-27 00:58 UTC, zifgu reviewed
The code changes look good to me and tests are passing. The deleted confirmation message issue is tricky, so maybe we can figure out what to do about it and then finalize this PR.

2022-05-27 20:09 UTC, zifgu commented
Update on the behaviour of the PR in the above edge case:
- Add a toggle for "customized/not customized" in the "Confirmation customization" section. If this toggle is on, we will display the form to customize the title and message, and count the confirmation screen as customized.

2022-05-27 23:12 UTC, zifgu commented on templates/vue/src/components/modals/NodeModal/forms/ContentForm/ActivityForm/index.vue
> +    },
It could be helpful to add a comment explaining why the custom confirmation toggle is implemented this particular way.

2022-06-15 02:05 UTC, wynnset requested changes
Let's keep the style consistent, so the toggle should say either "Default" or "Customized" and it should be placed to the right side similar to the "Required" toggle button in the previous panel:
<img width="737" alt="image" src="https://user-images.githubusercontent.com/8981258/173720858-f371d7cd-6e55-4b35-9ca4-00685ae241c1.png">

2022-09-16 22:48 UTC, merged